# Generated by Django 3.1.6 on 2022-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('teacher_name', models.CharField(max_length=225, verbose_name='Name:')),
                ('punctuality', models.CharField(max_length=225, verbose_name='Department')),
                ('portion', models.CharField(max_length=225, verbose_name='College')),
                ('basic', models.CharField(choices=[('Demonstrates professional competence and mastery of subject matter', 'Demonstrates professional competence and mastery of subject matter'), ('Meets commitments, observes deadlines and achieves desired results', 'Meets commitments, observes deadlines and achieves desired results'), ('Admits mistakes and refocuses efforts when appropriate', 'Admits mistakes and refocuses efforts when appropriate'), ('Completes own work on time', 'Completes own work on time'), ('Ensures that written correspondence is neat and professional', 'Ensures that written correspondence is neat and professional'), ('Works to overcome obstacles to completing tasks or assignments', 'Works to overcome obstacles to completing tasks or assignments')], max_length=225, verbose_name='Basic')),
                ('intermediate', models.CharField(choices=[('Shows persistence when faced with difficult problems or challenges', 'Shows persistence when faced with difficult problems or challenges'), ('Modifies behaviour as appropriate to meet the expectations of the position and the situation', 'Modifies behaviour as appropriate to meet the expectations of the position and the situation'), ('Accepts responsibility for outcomes (positive or negative) of ones work, and admits mistakes and refocuses efforts when appropriate', 'Accepts responsibility for outcomes (positive or negative) of ones work, and admits mistakes and refocuses efforts when appropriate'), ('Sets high standards of work performance for self', 'Sets high standards of work performance for self'), ('Reviews own work and others for quality', 'Reviews own work and others for quality'), ('Dedicates required time and energy to assignments or tasks that no aspects of the work is neglected', 'Dedicates required time and energy to assignments or tasks that no aspects of the work is neglected')], max_length=225, verbose_name='Intermediate')),
                ('advanced', models.CharField(choices=[('Expresses personal developmental goals and engages in activities to achieve them', 'Expresses personal developmental goals and engages in activities to achieve them'), ('Acknowledges others desire for development and creates a team atmosphere towards mutual improvement', 'Acknowledges others desire for development and creates a team atmosphere towards mutual improvement'), ('Provides encouragement and support to others in accepting responsibility', 'Provides encouragement and support to others in accepting responsibility'), ('Does not accept others denial of responsibility without questioning', 'Does not accept others denial of responsibility without questioning'), ('Sets high standards of performance for team, group or others', 'Sets high standards of performance for team, group or others'), ('Sets examples of high-quality work for peers', 'Sets examples of high-quality work for peers')], max_length=400, verbose_name='Advanced')),
                ('superior', models.CharField(choices=[('Demonstrates a high level of personal responsibility, dependability and reliability', 'Demonstrates a high level of personal responsibility, dependability and reliability'), ('Exhibits values, attitudes and behaviours of the organization', 'Exhibits values, attitudes and behaviours of the organization'), ('Establishes criteria and/or work procedures to achieve a high level of quality, productivity and service', 'Establishes criteria and/or work procedures to achieve a high level of quality, productivity and service')], max_length=225, verbose_name='Superior')),
            ],
            options={
                'verbose_name_plural': 'Feedback Data',
            },
        ),
    ]
