# Generated by Django 3.1.6 on 2022-06-09 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='portion',
            field=models.TextField(blank=True, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='punctuality',
            field=models.TextField(blank=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher', verbose_name='Teacher'),
        ),
    ]
