# Generated by Django 3.1.6 on 2022-06-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Feedback', '0002_auto_20220609_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.teacher', verbose_name='Teacher:'),
        ),
    ]
